name: Build Docker Image

on:
  push:
    branches:
      - backend  # main 브랜치에 push 될 때만 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image using docker-compose
        run: docker-compose -f docker-compose.yml build
